name: Chart Tests

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.18.5

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.0.3

      - name: Run chart tests
        run: helm unittest charts/openab
